[package]
license.workspace = true
name = "dataplane-rp2040-scd41-smoke"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "dataplane-rp2040-scd41-smoke"
path = "src/main.rs"
required-features = ["bare-metal-bin"]
test = false
bench = false

[features]
default = ["usb-auto-bootsel"]
bare-metal-bin = ["hil-recovery"]
hil-recovery = ["dataplane-runtime/rp2040-hil-recovery"]
usb-auto-bootsel = ["dataplane-runtime/rp2040-usb-auto-bootsel"]

[dev-dependencies]
proptest = "1"

[target.'cfg(target_os = "none")'.dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
dataplane-runtime = { path = "../dataplane-runtime", default-features = false }
embedded-hal-async = "1"
fugit = "0.3"
rp2040-hal = { version = "0.12", features = ["rt", "critical-section-impl"] }
rp2040-boot2 = "0.3"
scd4x = { version = "0.5", default-features = false, features = ["scd41", "embedded-hal-async"] }
usb-device = "0.3"
usbd-serial = "0.2"
