[package]
license.workspace = true
name = "dataplane-x86_64-microkernel-smoke"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dataplane-x86_64-microkernel-smoke"
path = "src/main.rs"
required-features = ["bare-metal-bin"]
test = false
bench = false

[features]
default = []
bare-metal-bin = []
fat32-write-proof = []
preallocated-journal-file-proof = ["fat32-write-proof"]

[dependencies]
dataplane-microkernel-core = { path = "../dataplane-microkernel-core" }
