pub use dataplane_compat::boundary::{BatchOp, BatchResult, BoundaryError};

#[derive(Clone)]
pub struct RuntimeStatsSnapshot {
    pub shard: usize,
    pub commands_drained: u64,
    pub ready_driven: u64,
    pub write_ready_enqueued: u64,
    pub write_ready_drained: u64,
    pub latency_cqes: u64,
    pub main_cqes: u64,
    pub recv_sqes: u64,
    pub recv_cqes: u64,
    pub recv_wouldblock: u64,
    pub recv_bytes: u64,
    pub read_poll_from_recv_eagain: u64,
    pub recv_wait_completed: u64,
    pub recv_wait_completed_error: u64,
    pub recv_wait_canceled: u64,
    pub recv_wait_timeout_canceled: u64,
    pub recv_wait_ns_total: u64,
    pub recv_wait_ns_max: u64,
    pub recv_wait_le_1us: u64,
    pub recv_wait_le_5us: u64,
    pub recv_wait_le_20us: u64,
    pub recv_wait_le_100us: u64,
    pub recv_wait_le_500us: u64,
    pub recv_wait_le_1ms: u64,
    pub recv_wait_le_5ms: u64,
    pub recv_wait_gt_5ms: u64,
    pub recv_ingress_wait_count: u64,
    pub recv_ingress_wait_ns_total: u64,
    pub recv_ingress_wait_ns_max: u64,
    pub recv_sync_ingress_wait_count: u64,
    pub recv_sync_ingress_wait_ns_total: u64,
    pub recv_sync_ingress_wait_ns_max: u64,
    pub send_sync_ingress_wait_count: u64,
    pub send_sync_ingress_wait_ns_total: u64,
    pub send_sync_ingress_wait_ns_max: u64,
    pub listener_accept_wait_count: u64,
    pub listener_accept_wait_ns_total: u64,
    pub listener_accept_wait_ns_max: u64,
    pub subscribe_accept_wait_count: u64,
    pub subscribe_accept_wait_ns_total: u64,
    pub subscribe_accept_wait_ns_max: u64,
    pub recv_buf_append_count: u64,
    pub recv_buf_append_bytes: u64,
    pub recv_buf_tail_append_count: u64,
    pub recv_buf_tail_append_bytes: u64,
    pub write_sqes: u64,
    pub write_cqes: u64,
    pub read_polls: u64,
    pub write_polls: u64,
    pub cancel_recv_cqes: u64,
    pub cancel_listener_accept_cqes: u64,
    pub close_fd_cqes: u64,
    pub reprovide_sqes: u64,
    pub rx_queue_peak: usize,
    pub tx_queue_peak: usize,
    pub conn_count: usize,
    pub ready_depth: usize,
    pub write_ready_depth: usize,
    pub result_events_enqueued: u64,
    pub result_reduce_runs_size: u64,
    pub result_reduce_runs_age: u64,
    pub result_reduce_runs_idle: u64,
    pub result_events_reduced: u64,
    pub send_tasks_enqueued: u64,
    pub send_batches_sent: u64,
    pub send_items_sent: u64,
    pub send_failures: u64,
    pub result_send_wait_count: u64,
    pub result_send_wait_ns_total: u64,
    pub result_send_wait_ns_max: u64,
    pub callback_fifo_peak: usize,
    pub callback_fifo_spill_count: u64,
}

/// Network address in wire-friendly form, independent of any NIF types.
#[derive(Clone, Debug)]
pub enum NetAddr {
    V4([u8; 4], u16),
    V6([u16; 8], u16),
}
