[package]
license.workspace = true
name = "dataplane-x86_64-virtio-smoke"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dataplane-x86_64-virtio-smoke"
path = "src/main.rs"
required-features = ["bare-metal-bin"]
test = false
bench = false

[features]
default = []
bare-metal-bin = []
shard-bench = []
udp-bench = []

[dependencies]
dataplane-microkernel-core = { path = "../dataplane-microkernel-core" }
dataplane-runtime = { path = "../dataplane-runtime", default-features = false, features = ["noalloc"] }
