[package]
name = "dataplane-runtime"
version = "0.1.0"
edition = "2021"

[features]
default = ["scheduler-fifo", "host-runtime"]
host-runtime = [
    "dep:libc",
    "dep:dataplane-core-reactor",
    "dataplane-core-reactor/host-core",
    "dep:dataplane-topology",
]
scheduler-fifo = []
scheduler-shares = []
esp32-integration = ["host-runtime", "dep:embedded-hal"]
noalloc = [
    "dep:dataplane-core-reactor",
    "dataplane-core-reactor/noalloc",
]
rp2040-integration = [
    "dep:dataplane-core-reactor",
    "dataplane-core-reactor/rp2040-compile",
]
rp2040-hil-recovery = ["dep:rp2040-hal"]
rp2040-usb-auto-bootsel = [
    "rp2040-hil-recovery",
    "dep:usb-device",
    "dep:usbd-serial",
]
rp2040-noalloc = ["noalloc"]
erlang-nif = ["host-runtime", "dep:crossbeam-channel", "dep:rustler"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(dataplane_verify_default_excludes_esp32)'] }

[dependencies]
libc = { version = "0.2", optional = true }
rustler = { version = "0.37", optional = true }
crossbeam-channel = { version = "0.5", optional = true }
embedded-hal = { version = "1", optional = true }
dataplane-core-reactor = { path = "../dataplane-core-reactor", default-features = false, optional = true }
dataplane-topology = { path = "../dataplane-topology", optional = true }

[target.'cfg(target_os = "none")'.dependencies]
rp2040-hal = { version = "0.12", optional = true }
usb-device = { version = "0.3", optional = true }
usbd-serial = { version = "0.2", optional = true }

[dev-dependencies]
criterion = "0.5"
crossbeam-queue = "0.3"
kanal = "0.1"

[[bench]]
name = "scheduler_hot_path"
harness = false

[[bench]]
name = "scheduler_backbone"
harness = false
