[package]
license.workspace = true
name = "dataplane-rp2040-smoke"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dataplane-rp2040-smoke"
path = "src/main.rs"
required-features = ["bare-metal-bin"]
test = false
bench = false

[features]
default = []
bare-metal-bin = []

[target.'cfg(target_os = "none")'.dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
dataplane-runtime = { path = "../dataplane-runtime", default-features = false, features = ["rp2040-integration"] }
